FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir -e "."

COPY src/ src/
COPY configs/ configs/
COPY .streamlit/ .streamlit/

EXPOSE 8501

CMD ["streamlit", "run", "src/medical_viewer/app.py", "--server.port=8501", "--server.headless=true"]
